function config = getConfig(modelName,configName)
if strcmp(modelName,'SVCJ') && strcmp(configName,'calibration')
    tt = readtable("Models\CalibrationConfig.txt","FileType","text","Delimiter",",");
    idx = find(strcmp(tt.modelName,'SVCJ'));
    % build SVCJ model
    config = struct(...
        'returnMethod',tt.returnMethod{idx},...
        'annulisationFactor',tt.annulisationFactor(idx),...
        'NumRuns',tt.numRuns(idx),...
        'burnInPeriod',tt.burnInPeriod(idx));
    Logger.getInstance.log(LogType.INFO,...
                    [modelName, ' calibration config complied']);

elseif strcmp(modelName,'SVCJ') && strcmp(configName,'simulation')
    tt = readtable("Models\SimulationConfig.txt","FileType","text","Delimiter",",");
    idx = find(strcmp(tt.modelName,'SVCJ'));
    config = struct(...
        'priceMethod',tt.priceMethod{idx},...
        'numOfIter',tt.numOfIter(idx),...
        'numOfPeriod',tt.numOfPeriod(idx));
    Logger.getInstance.log(LogType.INFO,...
                    [modelName, ' simulation config complied']);
else
    config = struct();
    Logger.getInstance.log(LogType.FATAL,...
                    [modelName, ' config not found']);
end
end

