function config = getConfig(modelName,configName)
if strcmp(modelName,'SVCJ') && strcmp(configName,'calibration')
    tt = readtable("Models\SVCJ\CalibrationConfig.txt","FileType","text","Delimiter",",");
    idx = find(strcmp(tt.modelName,'SVCJ'));
    % build SVCJ model
    config = struct(...
        'returnMethod',tt.returnMethod{idx},...
        'annulisationFactor',tt.annulisationFactor(idx),...
        'NumRuns',tt.numRuns(idx),...
        'burnInPeriod',tt.burnInPeriod(idx));
    Logger.getInstance.log(LogType.INFO,...
        [modelName, ' calibration config complied']);

elseif strcmp(modelName,'SVCJ') && strcmp(configName,'simulation')
    tt = readtable("Models\SVCJ\SimulationConfig.txt","FileType","text","Delimiter",",");
    idx = find(strcmp(tt.modelName,'SVCJ'));
    config = struct(...
        'priceMethod',tt.priceMethod{idx},...
        'numOfIter',tt.numOfIter(idx),...
        'numOfPeriod',tt.numOfPeriod(idx));
    Logger.getInstance.log(LogType.INFO,...
        [modelName, ' simulation config complied']);

    % Heston calibration
elseif strcmp(modelName,'Heston') && strcmp(configName,'calibration')
    tt = readtable("Models\Heston\CalibrationConfig.txt","FileType","text","Delimiter",",");
    idx = find(strcmp(tt.modelName,'Heston'));
    config = struct(...
        'v0',tt.v0(idx),...
        'theta',tt.theta(idx),...
        'rho',tt.rho(idx),...
        'kappa',tt.kappa(idx),...
        'sigma',tt.sigma(idx),...
        'alpha0',tt.alpha0(idx));
    Logger.getInstance.log(LogType.INFO,...
        [modelName, ' calibration initial config complied']);

    % Bates calibration
elseif strcmp(modelName,'Bates') && strcmp(configName,'calibration')
    tt = readtable("Models\Bates\CalibrationConfig.txt","FileType","text","Delimiter",",");
    idx = find(strcmp(tt.modelName,'Bates'));
    config = struct(...
        'v0',tt.v0(idx),...
        'vT',tt.vT(idx),...
        'rho',tt.rho(idx),...
        'kappa',tt.kappa(idx),...
        'sigma',tt.sigma(idx),...
        'lambda',tt.lambda(idx),...
        'muJ',tt.muJ(idx),...
        'sigmaJ',tt.sigmaJ(idx));
    Logger.getInstance.log(LogType.INFO,...
        [modelName, ' calibration initial config complied']);

else
    config = struct();
    Logger.getInstance.log(LogType.FATAL,...
        [modelName, ' config not found']);
end
end

